import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '../components/header/Header';
import HeroSection from '../components/section/hero_section/HeroSection';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Bitcoin price</title>
      <meta name='description' content='Generated by create next app' />
    </Head>

    <main>
      <Header />
      <HeroSection />
    </main>
  </div>
);

export default Home;
