import type { NextPage } from 'next';
import Head from 'next/head';

import React, { useState } from 'react';
import Header from '../components/header/Header';
import HeroSection from '../components/section/heroSection/HeroSection';

const Home: NextPage = () => {
  const [currentCurrency, setCurrentCurrency] = useState('USD');
  const [currencies, setCurrencies] = useState(['USD', 'CZK', 'EUR']);

  const selectCurrency = (event: React.MouseEvent<HTMLSpanElement> & { currentTarget: { textContent: React.SetStateAction<string>; }; }) => {
    setCurrentCurrency(event.currentTarget.textContent);
  };
  return (
    <div>
      <Head>
        <title>Bitcoin price</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>
        <Header currentCurrency={currentCurrency} currencies={currencies} selectCurrency={selectCurrency} />
        <HeroSection />
      </main>
    </div>
  );
};

export default Home;
